name: "Setup GCP Auth"
description: "Authenticate to GCP using Workload Identity Federation"

inputs:
  workload_identity_provider:
    required: true
  service_account:
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to GCP via WIF
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Install gcloud SDK
      uses: google-github-actions/setup-gcloud@v2