name: "Setup GCP Auth"
description: "Authenticate to GCP"

inputs:
  workload_identity_provider:
    required: true
    type: string
  service_account:
    required: true
    type: string


runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
