from typing import Protocol, Optional, TYPE_CHECKING
from sqlalchemy.ext.asyncio import AsyncSession

if TYPE_CHECKING:
    from app.domain.organization.models import Organization, OrganizationMember
    from app.domain.organization.schemas import (
        OrganizationCreate,
        OrganizationUpdate,
        OrganizationMemberCreate,
        OrganizationMemberUpdate,
    )
    from app.domain.users.models import User
    from app.domain.users.schemas import UserCreate, UserUpdate

class UserRepositoryProtocol(Protocol):
    async def get_by_clerk_id(self, db: AsyncSession, clerk_user_id: str) -> Optional["User"]: ...
    async def get_by_id(self, db: AsyncSession, user_id: str) -> Optional["User"]: ...
    async def create(self, db: AsyncSession, data: "UserCreate") -> "User": ...
    async def update(self, db: AsyncSession, user: "User", data: "UserUpdate") -> "User": ...
    async def delete(self, db: AsyncSession, user: "User") -> None: ...

class OrganizationRepositoryProtocol(Protocol):
    async def get_by_clerk_id(self, db: AsyncSession, clerk_id: str) -> Optional["Organization"]: ...
    async def get_by_id(self, db: AsyncSession, org_id: str) -> Optional["Organization"]: ...
    async def create(self, db: AsyncSession, data: "OrganizationCreate") -> "Organization": ...
    async def update(self, db: AsyncSession, org: "Organization", data: "OrganizationUpdate") -> "Organization": ...
    async def delete(self, db: AsyncSession, org: "Organization") -> None: ...

class OrganizationMemberRepositoryProtocol(Protocol):
    async def get_by_user_and_org(self, db: AsyncSession, user_id: str, org_id: str) -> Optional["OrganizationMember"]: ...
    async def create(self, db: AsyncSession, data: "OrganizationMemberCreate") -> "OrganizationMember": ...
    async def update(self, db: AsyncSession, member: "OrganizationMember", data: "OrganizationMemberUpdate") -> "OrganizationMember": ...
    async def delete(self, db: AsyncSession, member: "OrganizationMember") -> None: ...