from typing import Protocol, Optional
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.users.models import User
from app.domain.users.schemas import UserCreate, UserUpdate

class UserServiceProtocol(Protocol):
    async def create_user(self, db: AsyncSession, payload: UserCreate) -> User: ...
    async def get_user(self, db: AsyncSession, user_id: str) -> User: ...
    async def get_user_by_clerk_id(self, db: AsyncSession, clerk_user_id: str) -> User: ...
    async def update_user(self, db: AsyncSession, clerk_user_id: str, payload: UserUpdate) -> User: ...
    async def delete_user(self, db: AsyncSession, clerk_user_id: str) -> None: ...

