from typing import Protocol

from app.domain.users.models import User
from app.domain.users.schemas import UserCreate, UserUpdate


class UserServiceProtocol(Protocol):
    async def create_user(self, payload: UserCreate) -> User: ...
    async def get_user(self, user_id: str) -> User: ...
    async def get_user_by_clerk_id(self, clerk_user_id: str) -> User: ...
    async def update_user_by_clerk_id(self, clerk_user_id: str, payload: UserUpdate) -> User: ...
    async def delete_user_by_clerk_id(self, clerk_user_id: str) -> None: ...
