"""Add vessels

Revision ID: 1633d7c59ba3
Revises: 37474b90a097
Create Date: 2026-01-31 18:45:59.232982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1633d7c59ba3'
down_revision: Union[str, Sequence[str], None] = '37474b90a097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('vessel_type', sa.Enum('CARGO', 'TANKER', 'PASSENGER', 'FISHING', 'TUG_TOW', 'SERVICE', 'MILITARY', 'SAILING', 'PLEASURE', 'HIGH_SPEED', 'WIG', 'OTHER', name='vessel_type', native_enum=False), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vessel_created_by', 'vessel', ['created_by'], unique=False)
    op.create_index('ix_vessel_name', 'vessel', ['name'], unique=False)
    op.create_index('ix_vessel_org_id', 'vessel', ['org_id'], unique=False)
    op.create_index('ix_vessel_vessel_type', 'vessel', ['vessel_type'], unique=False)
    op.create_table('vessel_identity',
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('imo_number', sa.Text(), nullable=True),
    sa.Column('mmsi_number', sa.Text(), nullable=True),
    sa.Column('call_sign', sa.Text(), nullable=True),
    sa.Column('reported_name', sa.Text(), nullable=True),
    sa.Column('ais_ship_type', sa.Integer(), nullable=True),
    sa.Column('reported_type', sa.Text(), nullable=True),
    sa.Column('flag_state', sa.Text(), nullable=True),
    sa.Column('port_of_registry', sa.Text(), nullable=True),
    sa.Column('class_society', sa.Text(), nullable=True),
    sa.Column('class_notation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vessel_id'),
    sa.UniqueConstraint('imo_number', name='uq_vessel_identity_imo_number'),
    sa.UniqueConstraint('mmsi_number', name='uq_vessel_identity_mmsi_number')
    )
    op.create_index('ix_vessel_identity_ais_ship_type', 'vessel_identity', ['ais_ship_type'], unique=False)
    op.create_index('ix_vessel_identity_imo_number', 'vessel_identity', ['imo_number'], unique=False)
    op.create_index('ix_vessel_identity_mmsi_number', 'vessel_identity', ['mmsi_number'], unique=False)
    op.create_index('ix_vessel_identity_port_of_registry', 'vessel_identity', ['port_of_registry'], unique=False)
    op.create_index('ix_vessel_identity_vessel_id', 'vessel_identity', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vessel_identity_vessel_id', table_name='vessel_identity')
    op.drop_index('ix_vessel_identity_port_of_registry', table_name='vessel_identity')
    op.drop_index('ix_vessel_identity_mmsi_number', table_name='vessel_identity')
    op.drop_index('ix_vessel_identity_imo_number', table_name='vessel_identity')
    op.drop_index('ix_vessel_identity_ais_ship_type', table_name='vessel_identity')
    op.drop_table('vessel_identity')
    op.drop_index('ix_vessel_vessel_type', table_name='vessel')
    op.drop_index('ix_vessel_org_id', table_name='vessel')
    op.drop_index('ix_vessel_name', table_name='vessel')
    op.drop_index('ix_vessel_created_by', table_name='vessel')
    op.drop_table('vessel')
    # ### end Alembic commands ###
