"""init users

Revision ID: 173332464ab6
Revises: b25c1321d6fd
Create Date: 2025-12-12 03:22:28.977482

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "173332464ab6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
