"""describe change

Revision ID: 1b1672314fa3
Revises: 02954d21e72e
Create Date: 2026-01-23 10:59:06.368723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1672314fa3'
down_revision: Union[str, Sequence[str], None] = '02954d21e72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('CLASS_STATUS_REPORT', 'GA_PLAN', 'MACHINERY_LIST', 'SURVEY_REPORT', 'CERTIFICATE', 'OTHER', name='document_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_created_by', 'document', ['created_by'], unique=False)
    op.create_index('ix_document_org_id', 'document', ['org_id'], unique=False)
    op.create_index('ix_document_type', 'document', ['document_type'], unique=False)
    op.create_table('document_file',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_md5_b64', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'UNSUPPORTED', name='processing_status', native_enum=False), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_errors', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'content_md5_b64', name='uq_document_file_org_md5')
    )
    op.create_index('ix_document_file_document_id', 'document_file', ['document_id'], unique=False)
    op.create_index('ix_document_file_is_latest', 'document_file', ['is_latest'], unique=False)
    op.create_index('ix_document_file_org_id', 'document_file', ['org_id'], unique=False)
    op.create_index('ix_document_file_processing_status', 'document_file', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_file_processing_status', table_name='document_file')
    op.drop_index('ix_document_file_org_id', table_name='document_file')
    op.drop_index('ix_document_file_is_latest', table_name='document_file')
    op.drop_index('ix_document_file_document_id', table_name='document_file')
    op.drop_table('document_file')
    op.drop_index('ix_document_type', table_name='document')
    op.drop_index('ix_document_org_id', table_name='document')
    op.drop_index('ix_document_created_by', table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
