"""add document and document_file tables with parsing support

Revision ID: 2de4c61bd119
Revises: 1b1672314fa3
Create Date: 2026-01-30 23:48:54.921590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de4c61bd119'
down_revision: Union[str, Sequence[str], None] = '1b1672314fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_file', sa.Column('parsing_status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'ERROR', 'SKIPPED', name='parsing_status', native_enum=False), server_default=sa.text("'PENDING'"), nullable=False))
    op.add_column('document_file', sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_file', sa.Column('parsing_errors', sa.Text(), nullable=True))
    op.add_column('document_file', sa.Column('parsed_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_document_file_processing_status'), table_name='document_file')
    op.drop_constraint(op.f('uq_document_file_org_md5'), 'document_file', type_='unique')
    op.create_index('ix_document_file_parsed_suggestions', 'document_file', ['parsed_suggestions'], unique=False)
    op.create_index('ix_document_file_parsing_status', 'document_file', ['parsing_status'], unique=False)
    op.create_unique_constraint('uq_document_file_doc_md5', 'document_file', ['document_id', 'content_md5_b64'])
    op.drop_column('document_file', 'processing_status')
    op.drop_column('document_file', 'processed_at')
    op.drop_column('document_file', 'processing_errors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_file', sa.Column('processing_errors', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document_file', sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_file', sa.Column('processing_status', sa.VARCHAR(length=11), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('uq_document_file_doc_md5', 'document_file', type_='unique')
    op.drop_index('ix_document_file_parsing_status', table_name='document_file')
    op.drop_index('ix_document_file_parsed_suggestions', table_name='document_file')
    op.create_unique_constraint(op.f('uq_document_file_org_md5'), 'document_file', ['org_id', 'content_md5_b64'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_document_file_processing_status'), 'document_file', ['processing_status'], unique=False)
    op.drop_column('document_file', 'parsed_suggestions')
    op.drop_column('document_file', 'parsing_errors')
    op.drop_column('document_file', 'parsed_at')
    op.drop_column('document_file', 'parsing_status')
    # ### end Alembic commands ###
