"""add updated to orgmember and update name

Revision ID: 340aac2dac78
Revises: 06f760f3203c
Create Date: 2025-12-27 10:45:44.197025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '340aac2dac78'
down_revision: Union[str, Sequence[str], None] = '06f760f3203c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_member_org_id'), table_name='org_member')
    op.drop_index(op.f('ix_org_member_role'), table_name='org_member')
    op.drop_table('org_member')
    op.drop_column('users', 'last_login_at')
    op.create_table('organization_member',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='org_role', native_enum=False), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.create_index('ix_org_member_org_id', 'organization_member', ['org_id'], unique=False)
    op.create_index('ix_org_member_role', 'organization_member', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_table('org_member',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), server_default=sa.text("'MEMBER'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('org_member_org_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('org_member_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_id', name=op.f('org_member_pkey'))
    )
    op.create_index(op.f('ix_org_member_role'), 'org_member', ['role'], unique=False)
    op.create_index(op.f('ix_org_member_org_id'), 'org_member', ['org_id'], unique=False)
    op.drop_index('ix_org_member_role', table_name='organization_member')
    op.drop_index('ix_org_member_org_id', table_name='organization_member')
    op.drop_table('organization_member')
    # ### end Alembic commands ###
