"""baseline-full-schema-2026

Revision ID: 37474b90a097
Revises: 
Create Date: 2026-01-31 13:32:04.053026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37474b90a097'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('clerk_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('document',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('CLASS_STATUS_REPORT', 'GA_PLAN', 'MACHINERY_LIST', 'SURVEY_REPORT', 'CERTIFICATE', 'OTHER', name='document_type', native_enum=False), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_created_by', 'document', ['created_by'], unique=False)
    op.create_index('ix_document_org_id', 'document', ['org_id'], unique=False)
    op.create_index('ix_document_type', 'document', ['document_type'], unique=False)
    op.create_table('organization_member',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='org_role', native_enum=False), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.create_index('ix_org_member_org_id', 'organization_member', ['org_id'], unique=False)
    op.create_index('ix_org_member_role', 'organization_member', ['role'], unique=False)
    op.create_table('document_file',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_md5_b64', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsing_status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'ERROR', 'SKIPPED', name='parsing_status', native_enum=False), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsing_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_md5_b64', name='uq_document_file_doc_md5')
    )
    op.create_index('ix_document_file_document_id', 'document_file', ['document_id'], unique=False)
    op.create_index('ix_document_file_is_latest', 'document_file', ['is_latest'], unique=False)
    op.create_index('ix_document_file_org_id', 'document_file', ['org_id'], unique=False)
    op.create_index('ix_document_file_parsed_suggestions', 'document_file', ['parsed_suggestions'], unique=False)
    op.create_index('ix_document_file_parsing_errors', 'document_file', ['parsing_errors'], unique=False)
    op.create_index('ix_document_file_parsing_status', 'document_file', ['parsing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_file_parsing_status', table_name='document_file')
    op.drop_index('ix_document_file_parsing_errors', table_name='document_file')
    op.drop_index('ix_document_file_parsed_suggestions', table_name='document_file')
    op.drop_index('ix_document_file_org_id', table_name='document_file')
    op.drop_index('ix_document_file_is_latest', table_name='document_file')
    op.drop_index('ix_document_file_document_id', table_name='document_file')
    op.drop_table('document_file')
    op.drop_index('ix_org_member_role', table_name='organization_member')
    op.drop_index('ix_org_member_org_id', table_name='organization_member')
    op.drop_table('organization_member')
    op.drop_index('ix_document_type', table_name='document')
    op.drop_index('ix_document_org_id', table_name='document')
    op.drop_index('ix_document_created_by', table_name='document')
    op.drop_table('document')
    op.drop_table('users')
    op.drop_table('organization')
    # ### end Alembic commands ###
