"""Update vessels

Revision ID: 535fd520d743
Revises: 1633d7c59ba3
Create Date: 2026-02-02 06:06:26.829801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535fd520d743'
down_revision: Union[str, Sequence[str], None] = '1633d7c59ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessel_vessel_type'), table_name='vessel')
    op.drop_column('vessel', 'vessel_type')
    op.add_column('vessel_identity', sa.Column('vessel_type', sa.Enum('CARGO', 'TANKER', 'PASSENGER', 'FISHING', 'TUG_TOW', 'SERVICE', 'MILITARY', 'SAILING', 'PLEASURE', 'HIGH_SPEED', 'WIG', 'OTHER', name='vessel_type', native_enum=False), server_default=sa.text("'OTHER'"), nullable=False))
    op.drop_index(op.f('ix_vessel_identity_ais_ship_type'), table_name='vessel_identity')
    op.create_index('ix_vessel_identity_vessel_type', 'vessel_identity', ['vessel_type'], unique=False)
    op.drop_column('vessel_identity', 'ais_ship_type')
    op.drop_column('vessel_identity', 'reported_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessel_identity', sa.Column('reported_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('vessel_identity', sa.Column('ais_ship_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('ix_vessel_identity_vessel_type', table_name='vessel_identity')
    op.create_index(op.f('ix_vessel_identity_ais_ship_type'), 'vessel_identity', ['ais_ship_type'], unique=False)
    op.drop_column('vessel_identity', 'vessel_type')
    op.add_column('vessel', sa.Column('vessel_type', sa.VARCHAR(length=10), server_default=sa.text("'OTHER'::character varying"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_vessel_vessel_type'), 'vessel', ['vessel_type'], unique=False)
    # ### end Alembic commands ###
