"""Remove redundant fields from parsing job

Revision ID: 576e5973a8a0
Revises: e083914dc8b6
Create Date: 2026-02-05 18:13:22.429614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576e5973a8a0'
down_revision: Union[str, Sequence[str], None] = 'e083914dc8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsing_job', sa.Column('source_gcs_uri', sa.String(), nullable=True))
    op.add_column('parsing_job', sa.Column('result_gcs_uri', sa.String(), nullable=True))
    op.drop_index(op.f('ix_parsing_job_document_file_status'), table_name='parsing_job')
    op.drop_index(op.f('ix_parsing_job_document_id'), table_name='parsing_job')
    op.drop_index(op.f('ix_parsing_job_status_created_at'), table_name='parsing_job')
    op.create_index('ix_parsing_job_org_created', 'parsing_job', ['org_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('parsing_job_document_id_fkey'), 'parsing_job', type_='foreignkey')
    op.drop_column('parsing_job', 'document_id')
    op.drop_column('parsing_job', 'duration_ms')
    op.drop_column('parsing_job', 'source_gcs_object')
    op.drop_column('parsing_job', 'result_gcs_prefix')
    op.drop_column('parsing_job', 'result_gcs_bucket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsing_job', sa.Column('result_gcs_bucket', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parsing_job', sa.Column('result_gcs_prefix', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parsing_job', sa.Column('source_gcs_object', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('parsing_job', sa.Column('duration_ms', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('parsing_job', sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('parsing_job_document_id_fkey'), 'parsing_job', 'document', ['document_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_parsing_job_org_created', table_name='parsing_job')
    op.create_index(op.f('ix_parsing_job_status_created_at'), 'parsing_job', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_parsing_job_document_id'), 'parsing_job', ['document_id'], unique=False)
    op.create_index(op.f('ix_parsing_job_document_file_status'), 'parsing_job', ['document_file_id', 'status'], unique=False)
    op.drop_column('parsing_job', 'result_gcs_uri')
    op.drop_column('parsing_job', 'source_gcs_uri')
    # ### end Alembic commands ###
