"""Update vessel tables

Revision ID: 60ee49bb865a
Revises: 535fd520d743
Create Date: 2026-02-03 12:18:39.086688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ee49bb865a'
down_revision: Union[str, Sequence[str], None] = '535fd520d743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_dimensions',
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('loa_m', sa.Float(), nullable=True),
    sa.Column('lbp_m', sa.Float(), nullable=True),
    sa.Column('breadth_moulded_m', sa.Float(), nullable=True),
    sa.Column('depth_moulded_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vessel_id')
    )
    op.create_index('ix_vessel_dimensions_vessel_id', 'vessel_dimensions', ['vessel_id'], unique=False)
    op.alter_column('vessel_identity', 'vessel_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('CARGO', 'TANKER', 'PASSENGER', 'FISHING', 'TUG_TOW', 'SERVICE', 'MILITAR', 'SAILING', 'PLEASUR', 'HIGH_SP', 'WIG', 'OTHER', name='vessel_type', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'OTHER'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vessel_identity', 'vessel_type',
               existing_type=sa.Enum('CARGO', 'TANKER', 'PASSENGER', 'FISHING', 'TUG_TOW', 'SERVICE', 'MILITAR', 'SAILING', 'PLEASUR', 'HIGH_SP', 'WIG', 'OTHER', name='vessel_type', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'OTHER'::character varying"))
    op.drop_index('ix_vessel_dimensions_vessel_id', table_name='vessel_dimensions')
    op.drop_table('vessel_dimensions')
    # ### end Alembic commands ###
