"""add requires parsing or not to document file

Revision ID: 6885a5cd872a
Revises: c0670eb70739
Create Date: 2026-02-03 19:13:49.657610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6885a5cd872a'
down_revision: Union[str, Sequence[str], None] = 'c0670eb70739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_file', sa.Column('requires_parsing', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_file', 'requires_parsing')
    # ### end Alembic commands ###
