"""empty message

Revision ID: 9ab89f1a83ef
Revises: f69defd5df9e
Create Date: 2026-02-04 15:12:27.499532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab89f1a83ef'
down_revision: Union[str, Sequence[str], None] = 'f69defd5df9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessel_certificate',
    sa.Column('vessel_id', sa.String(), nullable=False),
    sa.Column('domain', sa.Enum('CLASS', 'STATUTORY', 'MANAGEMENT', 'SECURITY', 'LABOUR', 'OTHER', name='certificate_domain', native_enum=False), server_default=sa.text("'OTHER'"), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRED', 'EXPIRING_SOON', 'WITHDRAWN', 'UNKNOWN', name='certificate_status', native_enum=False), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vessel_certificate_domain', 'vessel_certificate', ['domain'], unique=False)
    op.create_index('ix_vessel_certificate_expiry_date', 'vessel_certificate', ['expiry_date'], unique=False)
    op.create_index('ix_vessel_certificate_identifier', 'vessel_certificate', ['identifier'], unique=False)
    op.create_index('ix_vessel_certificate_org_id', 'vessel_certificate', ['org_id'], unique=False)
    op.create_index('ix_vessel_certificate_status', 'vessel_certificate', ['status'], unique=False)
    op.create_index('ix_vessel_certificate_vessel_id', 'vessel_certificate', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vessel_certificate_vessel_id', table_name='vessel_certificate')
    op.drop_index('ix_vessel_certificate_status', table_name='vessel_certificate')
    op.drop_index('ix_vessel_certificate_org_id', table_name='vessel_certificate')
    op.drop_index('ix_vessel_certificate_identifier', table_name='vessel_certificate')
    op.drop_index('ix_vessel_certificate_expiry_date', table_name='vessel_certificate')
    op.drop_index('ix_vessel_certificate_domain', table_name='vessel_certificate')
    op.drop_table('vessel_certificate')
    # ### end Alembic commands ###
