"""Add table for parsing job

Revision ID: c0670eb70739
Revises: 60ee49bb865a
Create Date: 2026-02-03 17:01:40.872853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0670eb70739'
down_revision: Union[str, Sequence[str], None] = '60ee49bb865a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_file_parsed_suggestions'), table_name='document_file')
    op.drop_index(op.f('ix_document_file_parsing_errors'), table_name='document_file')
    op.drop_index(op.f('ix_document_file_parsing_status'), table_name='document_file')
    op.drop_column('document_file', 'parsed_suggestions')
    op.drop_column('document_file', 'parsing_status')
    op.drop_column('document_file', 'parsed_at')
    op.drop_column('document_file', 'parsing_errors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_file', sa.Column('parsing_errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('document_file', sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('document_file', sa.Column('parsing_status', sa.VARCHAR(length=10), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False))
    op.add_column('document_file', sa.Column('parsed_suggestions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_document_file_parsing_status'), 'document_file', ['parsing_status'], unique=False)
    op.create_index(op.f('ix_document_file_parsing_errors'), 'document_file', ['parsing_errors'], unique=False)
    op.create_index(op.f('ix_document_file_parsed_suggestions'), 'document_file', ['parsed_suggestions'], unique=False)
    # ### end Alembic commands ###
