"""add document and document_file tables with parsing support 2

Revision ID: e58d63627e5c
Revises: 2de4c61bd119
Create Date: 2026-01-31 00:17:51.027417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e58d63627e5c'
down_revision: Union[str, Sequence[str], None] = '2de4c61bd119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'document_type',
               existing_type=sa.VARCHAR(length=19),
               server_default=sa.text("'OTHER'"),
               existing_nullable=False)
    op.alter_column('document_file', 'content_md5_b64',
               existing_type=sa.TEXT(),
               nullable=False)
    op.execute("""
        ALTER TABLE document_file 
        ALTER COLUMN parsing_errors TYPE JSONB 
        USING CASE 
            WHEN parsing_errors IS NULL THEN NULL
            ELSE parsing_errors::jsonb 
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_file', 'parsing_errors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('document_file', 'content_md5_b64',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('document', 'document_type',
               existing_type=sa.VARCHAR(length=19),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
