"""update fields

Revision ID: ef40c500ff73
Revises: 576e5973a8a0
Create Date: 2026-02-05 19:06:05.819113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef40c500ff73'
down_revision: Union[str, Sequence[str], None] = '576e5973a8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_file', sa.Column('source_uri', sa.Text(), nullable=True))
    op.alter_column('document_file', 'content_md5_b64',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index('ix_document_file_uploaded', 'document_file', ['document_id'], unique=False, postgresql_where=sa.text('source_uri IS NOT NULL'))
    op.drop_column('document_file', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_file', sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index('ix_document_file_uploaded', table_name='document_file', postgresql_where=sa.text('source_uri IS NOT NULL'))
    op.alter_column('document_file', 'content_md5_b64',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('document_file', 'source_uri')
    # ### end Alembic commands ###
