"""empty message

Revision ID: f69defd5df9e
Revises: 6885a5cd872a
Create Date: 2026-02-03 21:46:43.061955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f69defd5df9e'
down_revision: Union[str, Sequence[str], None] = '6885a5cd872a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsing_job',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('document_file_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING', 'CANCELLED', name='parsing_job_status', native_enum=False), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pubsub_message_id', sa.String(), nullable=True),
    sa.Column('pubsub_publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_gcs_bucket', sa.String(), nullable=True),
    sa.Column('result_gcs_prefix', sa.String(), nullable=True),
    sa.Column('source_gcs_object', sa.String(), nullable=True),
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_file_id'], ['document_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsing_job_document_file_id'), 'parsing_job', ['document_file_id'], unique=False)
    op.create_index('ix_parsing_job_document_file_status', 'parsing_job', ['document_file_id', 'status'], unique=False)
    op.create_index(op.f('ix_parsing_job_document_id'), 'parsing_job', ['document_id'], unique=False)
    op.create_index(op.f('ix_parsing_job_org_id'), 'parsing_job', ['org_id'], unique=False)
    op.create_index('ix_parsing_job_org_status_created', 'parsing_job', ['org_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_parsing_job_pubsub_message_id'), 'parsing_job', ['pubsub_message_id'], unique=False)
    op.create_index(op.f('ix_parsing_job_status'), 'parsing_job', ['status'], unique=False)
    op.create_index('ix_parsing_job_status_created_at', 'parsing_job', ['status', 'created_at'], unique=False)
    op.create_index('uq_parsing_job_pubsub_message_id', 'parsing_job', ['pubsub_message_id'], unique=True, postgresql_where=sa.text('pubsub_message_id IS NOT NULL'))
    op.create_index('ux_parsing_job_active_file', 'parsing_job', ['document_file_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING','QUEUED','PROCESSING','RETRYING')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_parsing_job_active_file', table_name='parsing_job', postgresql_where=sa.text("status IN ('PENDING','QUEUED','PROCESSING','RETRYING')"))
    op.drop_index('uq_parsing_job_pubsub_message_id', table_name='parsing_job', postgresql_where=sa.text('pubsub_message_id IS NOT NULL'))
    op.drop_index('ix_parsing_job_status_created_at', table_name='parsing_job')
    op.drop_index(op.f('ix_parsing_job_status'), table_name='parsing_job')
    op.drop_index(op.f('ix_parsing_job_pubsub_message_id'), table_name='parsing_job')
    op.drop_index('ix_parsing_job_org_status_created', table_name='parsing_job')
    op.drop_index(op.f('ix_parsing_job_org_id'), table_name='parsing_job')
    op.drop_index(op.f('ix_parsing_job_document_id'), table_name='parsing_job')
    op.drop_index('ix_parsing_job_document_file_status', table_name='parsing_job')
    op.drop_index(op.f('ix_parsing_job_document_file_id'), table_name='parsing_job')
    op.drop_table('parsing_job')
    # ### end Alembic commands ###
