from typing import Protocol

from app.domain.organization.models import Organization
from app.domain.organization.schemas import OrganizationCreate, OrganizationUpdate


class OrganizationServiceProtocol(Protocol):
    async def create_organization(self, payload: OrganizationCreate) -> Organization: ...
    async def get_organization(self, organization_id: str) -> Organization: ...
    async def update_organization(self, organization_id: str, payload: OrganizationUpdate) -> Organization: ...
    async def delete_organization(self, organization_id: str) -> None: ...
    async def get_organization_by_clerk_id(self, clerk_org_id: str) -> Organization: ...
    async def add_member_to_organization(self, organization_id: str, user_id: str, role: str) -> None: ...
    async def remove_member_from_organization(self, organization_id: str, user_id: str) -> None: ...
    async def update_organization_member_role(self, organization_id: str, user_id: str, new_role: str) -> None: ...
